from __future__ import annotations

import pandas as pd
import pytest


@pytest.fixture
def board_df():
    return pd.DataFrame([
        {
            "Rank": 1,
            "Game ID": 101,
            "Start Time UTC": "2026-01-10T20:00:00Z",
            "Away Team": "Away State",
            "Home Team": "Home Tech",
            "Neutral Site": False,
            "Home D1": True,
            "Away D1": True,
            "Game Classification": "D1_VS_D1",
            "D1 Evaluation Eligible": True,
            "D1 Rank": 1,
            "Model Pick": "Home Tech",
            "Win Probability": 0.72,
            "Confidence Score": 64,
            "Projected Away Score": 68.0,
            "Projected Home Score": 77.0,
            "Projected Total": 145.0,
            "Projected Winner Margin": 9.0,
            "Fair Spread": -9.0,
            "Fair Moneyline": -257,
            "Home Win Probability": 0.72,
            "Away Win Probability": 0.28,
            "Fair Home Spread": -9.0,
            "Fair Home Moneyline": -257,
            "Fair Away Moneyline": 257,
            "Margin SD": 14.2,
            "Home Margin P10": -9.0,
            "Home Margin P90": 27.0,
            "V1.0.1 Baseline Rank": 1,
            "V1.0.1 Baseline D1 Rank": 1,
            "V1.0.1 Baseline Pick": "Home Tech",
            "V1.0.1 Baseline Win Probability": 0.65,
            "V1.0.1 Baseline Confidence Score": 59,
            "V1.0.1 Baseline Projected Away Score": 70.0,
            "V1.0.1 Baseline Projected Home Score": 75.0,
            "V1.0.1 Baseline Projected Total": 145.0,
            "V1.0.1 Baseline Projected Winner Margin": 5.0,
            "V1.0.1 Baseline Fair Spread": -5.0,
            "V1.0.1 Baseline Fair Moneyline": -186,
            "Schedule Translation Applied": True,
            "Schedule Translation Status": "applied",
            "V1.1 Home D1 SOS": 8.0,
            "V1.1 Away D1 SOS": 2.0,
            "SOS Difference Home-Away": 6.0,
            "Schedule Translation Margin Adj": 4.0,
            "Schedule Translation Raw Adj": 4.2,
            "Schedule Translation Linear Beta": 0.5,
            "Schedule Translation Hinge Beta": 0.2,
            "Schedule Translation Training Games": 240,
            "Expected Pace": 69.0,
            "Home AdjO": 118.0,
            "Home AdjD": 99.0,
            "Home AdjNet": 19.0,
            "Away AdjO": 111.0,
            "Away AdjD": 104.0,
            "Away AdjNet": 7.0,
            "Home SOS": 7.5,
            "Away SOS": 2.5,
            "Home Matchup Adj /100": 0.7,
            "Away Matchup Adj /100": -0.2,
            "Home Availability Adj": 0.0,
            "Away Availability Adj": 0.0,
            "Availability Verified": False,
            "Data Quality": 71.0,
            "Deployment Eligible": True,
            "Model Version": "1.1.0",
            "Target Date": "2026-01-10",
        },
        {
            "Rank": 2,
            "Game ID": 102,
            "Start Time UTC": "2026-01-10T22:00:00Z",
            "Away Team": "Metro",
            "Home Team": "Coastal",
            "Neutral Site": True,
            "Home D1": True,
            "Away D1": True,
            "Game Classification": "D1_VS_D1",
            "D1 Evaluation Eligible": True,
            "D1 Rank": 2,
            "Model Pick": "Metro",
            "Win Probability": 0.54,
            "Confidence Score": 52,
            "Projected Away Score": 74.0,
            "Projected Home Score": 72.0,
            "Projected Total": 146.0,
            "Projected Winner Margin": 2.0,
            "Fair Spread": -2.0,
            "Fair Moneyline": -117,
            "Home Win Probability": 0.46,
            "Away Win Probability": 0.54,
            "Fair Home Spread": 2.0,
            "Fair Home Moneyline": 117,
            "Fair Away Moneyline": -117,
            "Margin SD": 14.0,
            "Home Margin P10": -20.0,
            "Home Margin P90": 16.0,
            "V1.0.1 Baseline Pick": "Coastal",
            "V1.0.1 Baseline Win Probability": 0.52,
            "V1.0.1 Baseline Fair Spread": -1.0,
            "V1.0.1 Baseline Projected Winner Margin": 1.0,
            "Schedule Translation Applied": True,
            "Schedule Translation Status": "applied",
            "V1.1 Home D1 SOS": 3.0,
            "V1.1 Away D1 SOS": 5.0,
            "Schedule Translation Margin Adj": -3.0,
            "Schedule Translation Training Games": 240,
            "Expected Pace": 70.0,
            "Home AdjO": 114.0,
            "Home AdjD": 102.0,
            "Home AdjNet": 12.0,
            "Away AdjO": 115.0,
            "Away AdjD": 101.0,
            "Away AdjNet": 14.0,
            "Home SOS": 3.0,
            "Away SOS": 5.0,
            "Home Matchup Adj /100": 0.1,
            "Away Matchup Adj /100": 0.2,
            "Home Availability Adj": 0.0,
            "Away Availability Adj": 0.0,
            "Availability Verified": True,
            "Data Quality": 68.0,
            "Deployment Eligible": True,
            "Model Version": "1.1.0",
            "Target Date": "2026-01-10",
        },
    ])
